### PR TITLE
Material Design Overhaul

### PR DESCRIPTION
**Pull request by matthewkohlhaas**
This PR completely removes Bootstrap/NgBootstrap and replaces all elements and components with those from Angular Material. I believe it gives our app a much cleaner look. It should also streamline our development by not having two different sources from which we draw prebuilt UI elements.

Don't approve this PR util #61 has been approved first.

### CODE REVIEW

**Review by ScottSWolfe — COMMENTED** [review]
Do your new route names need to be merged into this? I tried running it, but the server was returning 404s.

**Comment by matthewkohlhaas** [comment]
Yes, the 404s are happening because we merged the API Route Refactor branch into master on the back end.

**Comment by matthewkohlhaas** [comment]
This branch should be good to go now.

**Review by ScottSWolfe — APPROVED** [review]
Looks great! I like the icons you added to the nav menu and converting it to a side-nav. Very nice.

**Pull request merged**
